// xdn-angular-example/src/app/components/rating/rating.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'app-rating',
  templateUrl: './rating.component.html',
  styleUrls: ['./rating.component.css'],
})
export class RatingComponent {
  @Input() rating?: string

  get value(): number {
    return Math.round(Number(this.rating))
  }
}

<div class="flex items-center mt-1">
  <span *ngFor="let e of [].constructor(5); let i = index">
    <div *ngIf="value >= i + 1; then thenBlock; else elseBlock"></div>
    <ng-template #thenBlock
      ><svg
        class="w-4 h-4 fill-current text-yellow-600"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
      >
        <path
          d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"
        />
      </svg>
    </ng-template>
    <ng-template #elseBlock
      ><svg
        class="w-4 h-4 fill-current text-gray-400"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20"
      >
        <path
          d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z"
        />
      </svg>
    </ng-template>
  </span>
</div>

// xdn-sapper-example/src/components/Rating.svelte
<script>
  export let value;
</script>

<div class="flex items-center mt-1">
  {#each Array.from({ length: 5 }) as item, i}
    {#if Math.round(value) >= i + 1}
      <svg
        class="w-4 h-4 fill-current text-yellow-600"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20">
        <path
          d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z" />
      </svg>
    {:else}
      <svg
        class="w-4 h-4 fill-current text-gray-400"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 20 20">
        <path
          d="M10 15l-5.878 3.09 1.123-6.545L.489 6.91l6.572-.955L10 0l2.939 5.955 6.572.955-4.756 4.635 1.123 6.545z" />
      </svg>
    {/if}
  {/each}
</div>
