// xdn-nuxt-example/components/Header.vue
<template>
  <nav>
    <header class="bg-white rounded-lg p-2 justify-center">
      <div class="container mx-auto logoContainer">
        <a href="/">
          <img src="/moovweb.svg" alt="Moovweb Logo" />
          <div class="text-center text-gray-700">NuxtJS Example</div>
        </a>
      </div>
      <div class="flex-container mx-auto">
        <ul>
          <li v-for="category in categories" :key="category.name">
            <Prefetch :url="getApiPath(category.href)">
              <NuxtLink :to="category.href">{{
                category.categoryName
              }}</NuxtLink>
            </Prefetch>
          </li>
        </ul>
      </div>
    </header>
  </nav>
</template>

<script lang="ts">
import { Prefetch } from '@xdn/vue'
import { getCategories, getApiPath } from '../lib/cms'

export default {
  components: {
    Prefetch,
  },
  async fetch() {
    const result = await getCategories()
    this.categories = result.categories
  },
  data() {
    return {
      categories: [],
    }
  },
  methods: {
    getApiPath,
  },
}
</script>

<style>
nav {
  border-bottom: 1px solid rgba(255, 62, 0, 0.1);
  font-weight: 300;
  padding: 0 1em;
}

li {
  display: block;
  float: left;
}

a {
  text-decoration: none;
  display: block;
  padding: 0.5em;
}

.flex-container {
  display: flex;
  width: 100%;
  justify-content: center;
  align-items: center;
}

.flex-container ul {
  width: 50%;
  display: flex;
  align-items: stretch;
  justify-content: space-between;
}

.flex-container li {
  flex: 0 1 auto;
  list-style-type: none;
}

.logoContainer {
  width: 200px;
}
</style>

// xdn-angular-example/src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core'
import { CMSService } from '../../service/cms.service'
import { ICategory } from '../../service/cms.service'

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
  providers: [CMSService],
})
export class HeaderComponent implements OnInit {
  categories: Array<ICategory> = []

  constructor(private cmsService: CMSService) {}

  ngOnInit(): void {
    this.cmsService.getCategories().subscribe((data: any) => {
      console.log(data)
      this.categories = data
    })
  }
}

<nav>
  <header class="bg-white rounded-lg p-2 justify-center">
    <div class="container mx-auto logoContainer">
      <a href="/">
        <img src="/assets/moovweb.svg" alt="Moovweb Logo" />
        <div class="text-center text-gray-700">Angular Example</div>
      </a>
    </div>
    <div class="flex-container mx-auto">
      <ul>
        <li *ngFor="let category of categories">
          <a routerLink="{{ category.href }}" routerLinkActive="active">{{
            category.categoryName
          }}</a>
        </li>
        <!-- <li v-for="category in categories" :key="category.name">
          <Prefetch :url="getApiPath(category.href)">
            <NuxtLink :to="category.href">{{ category.categoryName }}</NuxtLink>
          </Prefetch>
        </li> -->
      </ul>
    </div>
  </header>
</nav>
