// xdn-angular-example/src/app/components/product/product.component.ts
import { Component, OnInit } from '@angular/core'
import { ActivatedRoute } from '@angular/router'
import { CMSService, IProduct } from '../../service/cms.service'

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css'],
  providers: [CMSService],
})
export class ProductComponent implements OnInit {
  product?: IProduct
  constructor(private cmsService: CMSService, private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      this.cmsService.getProductById(params.name).subscribe((data: any) => (this.product = data))
    })
  }
}

<div class="container center flex flex-row" *ngIf="product">
  <div class="container px-4">
    <img [src]="product.picture" [alt]="product.name" />
  </div>
  <div class="container px-4 flex flex-col">
    <h2 class="font-bold py-2 m2">{{ product.name }}</h2>
    <div class="py-2 m2">{{ product.description }}</div>
    <div class="py-2 m2">${{ product.price }}</div>
    <div class="py-2 m2">
      <app-rating [rating]="product.rating"></app-rating>
    </div>
    <div class="py-2 m2">
      <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Add To Cart
      </button>
    </div>
  </div>
</div>

// xdn-vue-example/src/views/Product.vue
<script>
import { getProductById, getApiPath } from '@/../lib/cms'
import Rating from '@/components/Rating.vue'

export default {
  components: {
    Rating,
  },
  async mounted() {
    const { params } = this.$route
    try {
      this.product = await getProductById(params.name)
    } catch (e) {
      this.$router.push({ name: '404' })
    }
  },
  data() {
    return {
      product: {},
    }
  },
  methods: {
    getApiPath,
  },
}
</script>

<template>
  <div class="container center flex flex-row">
    <div class="container px-4">
      <img :src="product.picture" :alt="product.name" />
    </div>
    <div class="container px-4 flex flex-col">
      <h2 class="font-bold py-2 m2">{{ product.name }}</h2>
      <div class="py-2 m2">{{ product.description }}</div>
      <div class="py-2 m2">${{ product.price }}</div>
      <div class="py-2 m2">
        <Rating :value="Number(product.rating)" />
      </div>
      <div class="py-2 m2">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          Add To Cart
        </button>
      </div>
    </div>
  </div>
</template>
